Add config analyzer worker (including 3 analyzers)
openrelik/openrelik-worker-config-analyzer pull request #1
Opened 2024-10-11 10:10 UTC by hacktobeer

Add the config analyzer worker. This first version supports:
* SSH Daemon - artifact:SshConfigFile
* Jupyter Notebook - artifact:JupyterConfigFile
* Jenkins - filename:config.xml
Note: Analyzers have been ported from Turbinia.

Extra:
* pytests for all analyzers
* github workflow to execute tests

2024-10-11 10:18 UTC, hacktobeer commented
@berggren pytests will pass if you push a new release of the openrelik-common-worker library which include the reporting helper functions.

2024-10-12 15:41 UTC, berggren commented
> @berggren pytests will pass if you push a new release of the openrelik-common-worker library which include the reporting helper functions.

Ack

2024-10-12 15:45 UTC, berggren commented
File structure suggestion:

The naming is a bit redundant IMO. To follow what we do in other workers, mayabe something like this:
```
src
├── __init__.py
├── analyzers
│   ├── __init__.py
│   ├── jenkins_analyzer.py
│   ├── jupyter_analyzer.py
│   ├── sshd_analyzer.py
│   └── utils.py
├── app.py
├── jenkins_task.py
├── jupyter_task.py
└── sshd_task.py
```

2024-10-12 17:15 UTC, hacktobeer commented
@berggren files renamed and import in app.py reflect that.

2024-10-16 09:49 UTC, berggren commented
@hacktobeer common lib has been updated with the new reporting markdown feature. Do you want to update this PR to reflect that?

2024-10-18 10:19 UTC, berggren requested changes
Overall looks good. A couple of comments and I'll take another look when the reporting has been updated to the new implementation

2024-10-18 10:19 UTC, berggren commented on src/jenkins_task.py
> +            == f"openrelik.worker.file.{EXPECTED_FILENAME}".lower()
This is going to change soon (the data_type) but we can adjust that afterwards

2024-10-18 10:19 UTC, berggren commented on src/jenkins_task.py
> +                filename=f"{input_file.get('filename')}-{SHORT_TASK_NAME}-report",
Needs updating to the new create_output_file() implementation

filename --> display_name

2024-10-19 08:34 UTC, hacktobeer commented
@berggren Refactored for the new reporter class, PTAL.

2024-10-21 10:17 UTC, berggren approved these changes

2024-10-21 10:17 UTC, merged